#!/bin/bash

# ============================================================================
# Crypto Day Trading Arena - Environment Setup Script
# ============================================================================
# This script helps you create a .env file with your credentials
# Usage: ./setup_env.sh

set -e

echo "============================================================================"
echo "  Crypto Day Trading Arena - Environment Setup"
echo "============================================================================"
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo "⚠️  Warning: .env file already exists!"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled. Your existing .env file is unchanged."
        exit 0
    fi
    echo ""
fi

# Create .env file
echo "Creating .env file..."
echo ""

# Function to prompt for input with default
prompt_with_default() {
    local prompt="$1"
    local default="$2"
    local value
    
    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " value
        echo "${value:-$default}"
    else
        read -p "$prompt: " value
        echo "$value"
    fi
}

# Kafka Configuration
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Kafka Configuration (for full trading system)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
KAFKA_SERVERS=$(prompt_with_default "Kafka bootstrap servers" "localhost:9092")
echo ""

# OpenAI Configuration
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2. OpenAI Configuration (for AI trading agents)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
OPENAI_KEY=$(prompt_with_default "OpenAI API key" "")
echo ""

# TopstepX Configuration
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3. TopstepX Configuration (for CME futures trading)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Skip this section if you only plan to use Coinbase (crypto)"
echo ""

read -p "Do you want to configure TopstepX? (y/N): " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    TOPSTEPX_USERNAME=$(prompt_with_default "TopstepX username/email" "")
    TOPSTEPX_API_KEY=$(prompt_with_default "TopstepX API key" "")
    
    echo ""
    echo "Available environments:"
    echo "  - demo (Demo/Paper Trading)"
    echo "  - topstepx (TopstepX Live)"
    echo "  - alpha-ticks (Alpha Ticks)"
    echo "  - Other platforms (see .env.template)"
    TOPSTEPX_ENV=$(prompt_with_default "TopstepX environment" "demo")
else
    TOPSTEPX_USERNAME=""
    TOPSTEPX_API_KEY=""
    TOPSTEPX_ENV="demo"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Writing configuration to .env file..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Write .env file
cat > .env << EOF
# ============================================================================
# Crypto Day Trading Arena - Environment Configuration
# ============================================================================
# Generated by setup_env.sh on $(date)

# ============================================================================
# Kafka Configuration
# ============================================================================
KAFKA_BOOTSTRAP_SERVERS=$KAFKA_SERVERS

# ============================================================================
# LLM Configuration
# ============================================================================
OPENAI_API_KEY=$OPENAI_KEY

EOF

# Add TopstepX config if provided
if [ -n "$TOPSTEPX_USERNAME" ] && [ -n "$TOPSTEPX_API_KEY" ]; then
    cat >> .env << EOF
# ============================================================================
# TopstepX Authentication
# ============================================================================
TOPSTEPX_USERNAME=$TOPSTEPX_USERNAME
TOPSTEPX_API_KEY=$TOPSTEPX_API_KEY
TOPSTEPX_ENVIRONMENT=$TOPSTEPX_ENV

# Optional: JWT token (auto-generated from API key if not set)
# TOPSTEPX_JWT_TOKEN=

EOF
else
    cat >> .env << EOF
# ============================================================================
# TopstepX Authentication (Not Configured)
# ============================================================================
# Uncomment and fill in to use TopstepX for CME futures:
# TOPSTEPX_USERNAME=your-username-or-email
# TOPSTEPX_API_KEY=your-api-key
# TOPSTEPX_ENVIRONMENT=demo

EOF
fi

echo ""
echo "✅ Success! Configuration saved to .env"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Next Steps:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Load environment variables:"
echo "   source .env"
echo ""
echo "2. Activate virtual environment:"
echo "   source venv/bin/activate"
echo ""
echo "3. Test your setup:"
echo ""
echo "   # Test Coinbase (no auth required)"
echo "   python unified_market_connector.py --provider coinbase --symbols BTC-USD"
echo ""

if [ -n "$TOPSTEPX_USERNAME" ] && [ -n "$TOPSTEPX_API_KEY" ]; then
    echo "   # Test TopstepX authentication"
    echo "   python topstepx_auth.py"
    echo ""
    echo "   # Test TopstepX market data"
    echo "   python unified_market_connector.py --provider topstepx --symbols CON.F.US.ES.H25"
    echo ""
fi

echo "4. Run the full trading system:"
echo "   See QUICKSTART.md for complete instructions"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Make .env readable only by owner for security
chmod 600 .env
echo "🔒 Security: .env file permissions set to 600 (owner read/write only)"
echo ""

echo "All done! Your environment is configured and ready to use."
echo ""
